### ISSUE TITLE
sinric pro the device did not respond with the time period 

### ISSUE THREAD

**Issue by abdoshamma** [sinricpro/sample_messages#22]
Hello dear can you please help me with this msg, sometimes it's showing this msg even the internet is good ![IMG-20210806-WA0032.jpg](https://user-images.githubusercontent.com/20017323/128530348-71e4a09f-5250-4805-a6fa-85e597d7547d.jpg)

**Comment by abdoshamma** [comment]
![image.png](https://user-images.githubusercontent.com/20017323/128533704-7304878c-1434-48a8-89e1-897ef0b4e67b.png)

**Comment by kakopappa** [comment]
Try the sketch in the GitHub only with credentials changed

**Comment by abdoshamma** [comment]
I only added the wifi Manger library to the sketch nothing more and this rarely happens but it did, do you have any idea?

**Comment by kakopappa** [comment]
Can you enable the sdk logs and send the output from Arduino Serial
Monitor?

**Comment by kakopappa** [comment]
Also make sure you are using the latest version of the SDK and app

**Comment by abdoshamma** [comment]
Thank you
